# Generated by Django 5.1.4 on 2024-12-20 04:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainPageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="For SEO, preview, and breadcrumbs.",
                        max_length=128,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Button text"
                    ),
                ),
                (
                    "text",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="Content"),
                ),
                (
                    "background",
                    models.ImageField(
                        blank=True,
                        upload_to="main/background",
                        verbose_name="Background",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
            ],
            options={
                "verbose_name": "Main Page Settings",
                "default_permissions": ("change",),
            },
        ),
    ]
