# Generated by Django 5.1.4 on 2024-12-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpageconfig",
            name="background",
            field=models.ImageField(
                blank=True,
                help_text="Recommended size: 1400x800 pixels",
                upload_to="main/background",
                verbose_name="Background",
            ),
        ),
    ]
