# Generated by Django 5.1.4 on 2024-12-20 06:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_mainpageconfig_background"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpageconfig",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Content"
            ),
        ),
    ]
