# Generated by Django 5.1.4 on 2024-12-20 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_mainpageconfig_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainpageconfig",
            options={
                "verbose_name": "Main Page Settings",
                "verbose_name_plural": "Main Page Settings",
            },
        ),
    ]
