# Generated by Django 5.1.4 on 2024-12-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_mainpageconfig_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpageconfig",
            name="background_mobile",
            field=models.ImageField(
                blank=True,
                help_text="Mobile version - recommended size: 800x600 pixels",
                upload_to="main/background",
                verbose_name="Mobile Background",
            ),
        ),
        migrations.AddField(
            model_name="mainpageconfig",
            name="background_tablet",
            field=models.ImageField(
                blank=True,
                help_text="Tablet version - recommended size: 1024x768 pixels",
                upload_to="main/background",
                verbose_name="Tablet Background",
            ),
        ),
        migrations.AddField(
            model_name="mainpageconfig",
            name="button_text",
            field=models.CharField(
                default="I want to feel better",
                help_text="Call to action button text",
                max_length=64,
                verbose_name="Button Text",
            ),
        ),
        migrations.AddField(
            model_name="mainpageconfig",
            name="slider_tagline",
            field=models.CharField(
                default="keep your life moving",
                help_text="Text that appears in the slider",
                max_length=128,
                verbose_name="Slider Tagline",
            ),
        ),
        migrations.AlterField(
            model_name="mainpageconfig",
            name="background",
            field=models.ImageField(
                blank=True,
                help_text="Main slider background - recommended size: 1400x800 pixels",
                upload_to="main/background",
                verbose_name="Background",
            ),
        ),
    ]
