# Generated by Django 5.1.4 on 2026-05-12 04:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mainpageconfig_background_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('condition', models.CharField(blank=True, max_length=256, verbose_name='Condition / Reason for Visit')),
                ('preferred_location', models.CharField(choices=[('greeley', 'Greeley'), ('denver', 'Denver'), ('no-preference', 'No Preference')], max_length=20, verbose_name='Preferred Location')),
                ('source_page', models.CharField(choices=[('shockwave-denver', 'Shockwave Therapy Denver'), ('shockwave-greeley', 'Shockwave Therapy Greeley'), ('shockwave-plantar-fasciitis', 'Shockwave Plantar Fasciitis'), ('chronic-tendon', 'Chronic Tendon Pain'), ('non-surgical-denver', 'Non-Surgical Pain Relief Denver')], max_length=50, verbose_name='Source Page')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted')),
            ],
            options={
                'verbose_name': 'Landing Page Lead',
                'verbose_name_plural': 'Landing Page Leads',
                'ordering': ['-created'],
            },
        ),
    ]
