name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
      SERVER_EMAIL: ${{ secrets.SERVER_EMAIL }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
        
    - name: Install dependencies
      run: |
        poetry install --no-interaction
        
    - name: Run tests
      run: |
        poetry run python manage.py test
        
    - name: Deploy to production
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Fix Git safe directory issue
          git config --global --add safe.directory /var/www/artwebsite
          
          # Navigate to project directory
          cd /var/www/artwebsiteOk ok Cortana
          
          # Update code
          git fetch
          git reset --hard origin/main
          
          # Install dependencies
          export PATH="$HOME/.local/bin:$PATH"
          poetry install --no-interaction
          
          # Run migrations and collect static files
          poetry run python manage.py migrate
          poetry run python manage.py collectstatic --noinput
          
          # Restart Gunicorn
          sudo systemctl restart gunicorn
          
          echo "Deployment successful!"